name: Java CI

env:
  JDK_CURRENT: 11.0.10
  DISTRIBUTION: zulu

on:
  push:
    branches:
      - 3.0.x
  pull_request:
    branches:
      - 3.0.x

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: Build and test
        run: sbt clean +test
  publish:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: Publish
        run: sbt +publish
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PWD }}
